I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 307, in script
    jump ai_drawing_disscussion_start
ScriptError: could not find label 'ai_drawing_disscussion_start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 307, in script
    jump ai_drawing_disscussion_start
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'ai_drawing_disscussion_start'.

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
Brutal Maud 1.0
Fri Oct 21 18:04:27 2022
